# Remote App in non-blocking mode.gd

name: Snyk API & Web CICD Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install Probely CLI edit
      - name: Install Probely CLI
        run: |
          # Install Probely CLI
          pip install probely
          # Test probely GET TARGETS
          probely targets get --api-key ${{ secrets.PROBELY_API_KEY }}
      
      # Step 2: Configure Target for Incremental Scan
      - name: Configure Target for Incremental Scan
        run: |
          TARGET_ID="${{ env.TARGET_ID }}"
      
      # Create a temporary YAML file to set incremental to true
      echo 'incremental: true' > /tmp/probely_settings.yaml
      
      # Update the target's settings using the environment variable authentication
      probely targets update "$TARGET_ID" -f /tmp/probely_settings.yaml
         
            fi
            sleep 5
          done
