# Incremental

name: Incremental Snyk API & Web CICD Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install Probely CLI edit
      - name: Install Probely CLI
        run: |
          # Install Probely CLI
          pip install probely
          # Test probely GET TARGETS
          probely targets get --api-key ${{ secrets.PROBELY_API_KEY }}
      
      # Step 2: Start Scan
      - name: Start Scan
        run: |
          echo 'incremental: true' > /tmp/yaml_file.yaml && probely targets update <TARGET_ID> -f /tmp/yaml_file.yaml && probely targets start-scan <TARGET_ID>
          
          
