# Remote App in non-blocking mode.gd

name: Snyk API & Web CICD Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install Probely CLI edit
      - name: Install Probely CLI
        run: |
          # Install Probely CLI
          pip install probely
          # Test probely GET TARGETS
          probely targets get --api-key ${{ secrets.PROBELY_API_KEY }}
      
      # Step 2: Inc
      - name: Configure Incremental Scan and Start
        # Use the pipe '|' for multi-line shell scripts for robustness.
        run: |
          TARGET_ID="${{ env.TARGET_ID }}" # Ensure the variable is pulled into the script scope
          
          # 1. Create a temporary YAML file with the incremental setting
          echo 'incremental: true' > /tmp/probely_settings.yaml
          
          # 2. Update the target's settings to enable incremental scan
          # The -f flag specifies the file to read the settings from.
          probely targets update "$TARGET_ID" -f /tmp/probely_settings.yaml          
                
      # Step 2: Start Scan
      - name: Start Scan
        run: |
          for i in {1..20}; do
            echo "-----------------------------------"
            SCAN_ID=$(probely targets start-scan ${{ vars.TARGET_ID }} -o IDS_ONLY --api-key ${{ secrets.PROBELY_API_KEY }})
            echo ${SCAN_ID}
            if [ -f ${SCAN_ID} ]; then
              echo "Scan didn't start... Retry start-scan"
            else
              echo "Scan started with SCAN ID: ${SCAN_ID}";
              echo "SCAN_ID=${SCAN_ID}" >> $GITHUB_ENV
              break;
            fi
            sleep 5
          done
